# Generated by Django 4.1.7 on 2023-03-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
