# Generated by Django 4.1.7 on 2023-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_productimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(default='photo', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
