# Generated by Django 4.1.7 on 2023-03-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_reviews_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='информация о товаре'),
        ),
    ]
