# Generated by Django 4.1.7 on 2023-03-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='info',
            new_name='descr',
        ),
    ]
