# Generated by Django 4.1.7 on 2023-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_info_product_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descr',
            field=models.TextField(blank=True, default='находится в разработке', max_length=4096, null=True, verbose_name='информация о товаре'),
        ),
    ]
