# Generated by Django 4.1.7 on 2023-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='название товара')),
                ('description', models.TextField(blank=True, max_length=4096, null=True, verbose_name='описание товара')),
            ],
        ),
    ]
