# Generated by Django 4.1.7 on 2023-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='вспомогательный текст'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=32, verbose_name='заглавная стока'),
        ),
    ]
