# Generated by Django 4.1.7 on 2023-03-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_about_description_alter_about_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'о нас', 'verbose_name_plural': 'о нас'},
        ),
    ]
