# Generated by Django 4.1.7 on 2023-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('number', models.CharField(max_length=17, verbose_name='номер телефона')),
                ('message', models.CharField(max_length=5000, verbose_name='Сообщение')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
